### ISSUE TITLE
Option to ignore merge commits

### ISSUE THREAD

**Issue by kalekundert** [jeremyagray/pccc#2] opened 2021-04-01 17:41 UTC
When using `pccc` as a `commit-msg` hook, automatic merges after `git pull` fail because the default commit message ("Merge branch '...' of ...") doesn't match the conventional commit format.  It would be nice if there was an option to ignore these commits.

**Comment by jeremyagray** [comment] 2021-04-02 15:09
I think this is probably a feature and not a bug, if the intent is to allow conventional commits only (which it is).  Since `git pull` runs `git fetch` or `git rebase` and then `git merge` ([ref](https://git-scm.com/docs/git-pull#_description)), and `git merge` allows specifying a commit message, I believe that would be a better workflow for this situation.  Alternatively, you could use `git pull --no-commit` to do the fetch and merge and then commit manually in the normal fashion.  I imagine doing the pull operation in any editor or IDE can prompt for a message (it is an option in emacs/magit).

But that's me.  Is there a use case where it would be desirable to have most of the commits structured as conventional commits but then have just the pulls unstructured?  In my case, the answer is no because I want all the commit data structured.

**Comment by kalekundert** [comment] 2021-04-02 16:02
That makes sense.

My use case is that I'm using [`python_semantic_release`](https://python-semantic-release.readthedocs.io/en/latest/), which runs when my CI tests pass and makes a new release with the version number determined by my conventional commit messages.  This of course requires making a commit that bumps the version number (and updates the change log).  But I often forget to pull this commit before making more changes, so when I go to push my next batch of commits, I often have to do a merge.  Usually the merge succeeds automatically, bacause there aren't conflicts involving the version number or the change log, but when I switched to `pccc` it started failing because the default commit message gets rejected.  This isn't a deal-breaker, because all I need to do at that point is commit manually with a valid message, but it's an annoying extra step that (in my view) isn't adding any value.

More broadly, I guess my perspective is that I only really care that the commits I author manually match the conventional commit format.  That ensures I won't make the wrong kind of release because of a typo.  If there are automatically generated commits in my history that don't match the format, that doesn't bother me.

I can see your persepective, though.  In any case, I like `pccc`.  I was previously using `commitlint`, but `pccc` integrates much more nicely with the python ecosystem.

**Comment by jeremyagray** [comment] 2021-04-02 16:42
Okay, I can see that.  It would be nice if there was at least an option on all the other git related tooling to default to conventional commits.  What I would like to do is to allow this when an generated commit message matches a certain format, which would require a configurable option to allow the behavior and a list of generated commit message formats.  If you have some generated messages like the "Merge branch '...' of ..." from earlier and can post them for me to test, I'll try to implement this behavior.

**Comment by kalekundert** [comment] 2021-04-02 19:45
I agree that it would be nice if git had this option.  I found `git fmt-merge-msg` earlier, which *almost* does this, but not quite.

I'd advocate for implementing this by simply allowing the user to specify a regex and ignoring any commits it matches.  That would avoid the need to compile a list of generated commit message formats (although I can't think of how any but the merge one would be an issue), and would maybe be useful in some non-standard workflows.

Here's some of the history from a current project of mine.  You can see that the version commits created by `python_semantic_release` (ironically) don't match the conventional commit format, and neither do the merge commits.  Only the merge commit cause problems for me, though:
```
7c456aa (HEAD -> master, origin/master) chore: switch to pccc for commit linting
7285350 fix: debug the `go` command
bc6fdd8 fix: avoid infinite recursion with autoprop>=2.0
0a948bd fix: update semantics for callable `appcli.Layer` values
606776e refactor: remove duplicate function
ec2b782 (tag: v0.19.0) 0.19.0
e7533d1 fix: remove more debugging code
fabfdd7 feat: teach `sw step` about subsubsteps
9891b1c fix: remove debugging code
efb8a42 feat: add `dl` and `table` formatting objects
e415f0c (tag: v0.18.0) 0.18.0
001003f feat: gracefully handle unreadable stashed protocols
c7335ea (tag: v0.17.1) 0.17.1
dc6e3d9 Merge branch 'master' of github.com:kalekundert/stepwise
9337bac fix: address some formatting corner cases
7119975 (tag: v0.17.0) 0.17.0
bc8cb01 feat: add better text formatting tools
8261088 feat: implement Reaction.iter_reagents_by_flag()
33776cc feat: allow `sw reaction` to eval volume arguments
2638b5c feat: add options to the 'reaction' command
bbbd11a feat: provide method to simultaneously add and format footnotes
5c6dab3 feat: parse catalog numbers and flags for reaction tables
0217e19 (tag: v0.16.0) 0.16.0
7f10b67 feat: make reaction tables less whitespace-sensitive
5c0123f (tag: v0.15.0) 0.15.0
b420f95 feat: use a pager to display long protocols
e924fcf (tag: v0.14.0) 0.14.0
4f9ad51 feat: rename 'reactions' built-in command to 'conditions'
32b6b0c (tag: v0.13.0) 0.13.0
70db9fb Merge branch 'master' of github.com:kalekundert/stepwise
e107d78 feat: add the 'reaction' built-in command
47bd7a6 (tag: v0.12.0) 0.12.0
66fd9f3 refactor: remove some code duplication
6a512b9 Merge branch 'master' of github.com:kalekundert/stepwise
c62fb26 chore: move pytest options to pyproject.toml
7d55fab feat: implement Reaction.get_free_volume_excluding()
1dc4ca3 fix: format subcommands briefs correctly
d597cd3 (tag: v0.11.1) 0.11.1
f065f59 Merge branch 'master' of github.com:kalekundert/stepwise
888fb78 fix: debug the printing feature of the `sw go`
a5fcc4d (tag: v0.11.0) 0.11.0
bbb7f55 fix: ignore extraneous openpyxl and pandas warnings
b672f36 chore: replace xlrd with openpyxl
ac5f6f9 feat: migrate to appcli
8bb1cf9 fix: check the header before attempting to unpickle a byte stream
0f4a31d Merge branch 'master' of github.com:kalekundert/stepwise
46cf301 chore: add links to info on xlrd/openpyxl versions
7f649fa (tag: v0.10.0) 0.10.0
f3e5ab6 chore: pin xlrd<2.0
c1ba61a chore: replace xlrd with openpyxl
e6b4f42 chore: remove xlrd dependency
66b3c62 fix: don't require `lpstat` to be installed
47fcbc0 fix: handle unexpected `lpstat -d` output
dc02e25 chore: update dependencies
403eece feat: migrate configuration to appcli
0bc08a0 feat: add sorthand symbols to the reaction command
4ada82e style: split long line
4dc188a fix: improve the Footnote comparison operators
c215ac7 (tag: v0.9.0) 0.9.0
72c7d19 feat: add an accessor for the current step of a protocol
ffc4302 (tag: v0.8.0) 0.8.0
587792c feat: add function to print protocols as pickles
3d9dd35 fix: allow MasterMix objects to be pickled
0c31b53 (tag: v0.7.3) 0.7.3
9ab5357 fix: handle SystemExit return codes that are strings
14fa8a4 (tag: v0.7.2) 0.7.2
7408111 Merge branch 'master' of github.com:kalekundert/stepwise
790b6f2 fix: support the range syntax when pruning footnotes
53342af (tag: v0.7.1) 0.7.1
5cd681e fix: ensure that return codes are always integers
bdb536f (tag: v0.7.0) 0.7.0
612a592 chore: correctly escape newlines
48bc4c7 chore: add xlrd dependency
5f465fa chore: add pandas dependency
51fec8e chore: change toml dependency
62ed97c feat: rename the `custom` builtin protocol to `step`
ccd2141 feat: add the `reactions` builtin protocol
39a8934 fix: return the error code instead of printing it
89e7dbf feat: add API for creating steps and substeps
117fb51 docs: describe how to center-align table cells
dfb7c41 Merge branch 'master' of github.com:kalekundert/stepwise into master
92cb3c6 docs: tweak wording
8b577bf (tag: v0.6.0) 0.6.0
97a3edc Merge branch 'master' of github.com:kalekundert/stepwise into master
fd11438 feat: hide dependent stashed protocols by default
495efdb (tag: v0.5.0) 0.5.0
90738da Merge branch 'master' of github.com:kalekundert/stepwise into master
44cae8e feat: keep existing stash annotations by default
```

**Comment by jeremyagray** [comment] 2021-04-02 22:13
I just pushed a branch ([jag-generated-commits](https://github.com/jeremyagray/pccc/tree/jag-generated-commits)) with a working implementation, I think.  I still need to implement tests and check the documentation.  The changes in `pyproject.toml` are fairly self-explanatory and that is the only route I've tested so far.  I'll need to check the CLI as well.

I don't like how fiddly the TOML parser is with regular expression strings, so that might need some more work (nevermind the shell).  I'm also not sold on using REs over string matching, but that's the plan for now.

Once I get everything tested and polished and I consign myself to using REs for this, I'll tag and release this as 0.4.3 and we should be able to close this.

**Comment by jeremyagray** [comment] 2021-04-11 15:42
Just pushed 0.4.3 out and it should address this issue at least minimally.  I did get some basic testing of the RE list for this, but I still anticipate quoting issues to arise from the TOML and JSON parsing.  I will beef up the testing as I continue to move all the testing to round-trip/property-like testing and hopefully any missed bugs can be squashed then.

I'm closing this issue since the enhancement is finished, but if something doesn't work while ignoring the commits just open a new issue.

**Closed by jeremyagray** 2021-04-11 15:42 UTC
Labels: enhancement

**Comment by kalekundert** [comment] 2021-04-11 16:15
Awesome, thanks!
